---

name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Setup a virtual environment
        run: |
          python -m venv .venv
          echo "PATH=.venv/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r test-requirements.txt

      - name: Run tests
        run: |
          pytest -v --tb=short --disable-warnings --maxfail=1
